"""Added password field for User

Revision ID: 195cc6626435
Revises: 6fcac516d81a
Create Date: 2019-03-24 19:25:45.635217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195cc6626435'
down_revision = '6fcac516d81a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pw_timestamp', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('pwhash', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pwhash')
    op.drop_column('user', 'pw_timestamp')
    # ### end Alembic commands ###
