"""Added relationship for ridergroup

Revision ID: 074534edcdb4
Revises: 7c718174344e
Create Date: 2019-02-25 22:39:50.014477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074534edcdb4'
down_revision = '7c718174344e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
