"""Added timezone column to the locations table

Revision ID: 7c718174344e
Revises: ab7d9cf4d1af
Create Date: 2019-02-25 22:21:24.331129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c718174344e'
down_revision = 'ab7d9cf4d1af'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'timezone')
    # ### end Alembic commands ###
