"""Added table to store prediction model results

Revision ID: d372d3e1a794
Revises: 728c17a59722
Create Date: 2021-01-17 15:57:18.287030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd372d3e1a794'
down_revision = '728c17a59722'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictionmodel_result',
    sa.Column('entry_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['predictionmodel.id'], name=op.f('fk_predictionmodel_result_model_id_predictionmodel')),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name=op.f('fk_predictionmodel_result_ride_id_ride')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictionmodel_result')),
    mysql_encrypted='yes'
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=512),
               existing_nullable=True)

    with op.batch_alter_table('locationtype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.alter_column('end_timezone',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('rolling_time',
               existing_type=sa.DATETIME(),
               type_=sa.Interval(),
               existing_nullable=True)
        batch_op.alter_column('start_timezone',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('total_time',
               existing_type=sa.DATETIME(),
               type_=sa.Interval(),
               existing_nullable=True)

    with op.batch_alter_table('rider', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('ridergroup', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('stationweatherdata', schema=None) as batch_op:
        batch_op.alter_column('weather',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('surfacetype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('pwhash',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('weatherdata', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weatherdata', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pwhash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('surfacetype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('stationweatherdata', schema=None) as batch_op:
        batch_op.alter_column('weather',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('ridergroup', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('rider', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.alter_column('total_time',
               existing_type=sa.Interval(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('timezone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('start_timezone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('rolling_time',
               existing_type=sa.Interval(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('end_timezone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('locationtype', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.drop_table('predictionmodel_result')
    # ### end Alembic commands ###
