version: '3.7'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - mysql-data:/var/lib/mysql
    configs:
      - source: mysql-config-cycling
        target: /etc/mysql/conf.d/mysql-config-cycling.cnf
    logging:
      driver: journald
    secrets:
      - mysql_root_password
  cycling_web:
    image: jhaiduce/cycling-pyramid
    ports:
      - "80:80"
    secrets:
      - storage_key
      - mysql_production_password
      - mysql_root_password
      - pyramid_auth_secret
      - cycling_admin_password
    volumes:
      - cycling-data:/var/lib/cycling_data
    logging:
      driver: journald
secrets:
  storage_key:
    file: ./storage_key.keyfile
  mysql_root_password:
    file: ./mysql_root_pw
  mysql_production_password:
    file: ./mysql_production_pw
  pyramid_auth_secret:
    file: ./pyramid_auth_secret
  cycling_admin_password:
    file: ./cycling_admin_password
    
volumes:
  cycling-data:
  mysql-data:
configs:
  mysql-config-cycling:
    file: ./mysql-config-cycling.cnf
