version: '3.7'
services:
  db:
    ports:
      - 3308:3306
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    links:
      - cycling_web
  fake_ogimet:
    build:
      context: .
      dockerfile: Dockerfile.fake_ogimet
    container_name: fake_ogimet
    logging:
      driver: journald
    ports:
      - 8082:80
    volumes:
      - type: bind
        source: ./ogimet-cache
        target: /app/ogimet-cache
  cycling_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/cycling-pyramid
    container_name: cycling_test_cycling_web
    command: ["/app/pyramid_start.sh"]
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
    links:
      - db
      - rabbitmq
      - redis
    ports:
      - 8081:80
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/cycling-pyramid
    command: ["/usr/local/bin/celery","-A","cycling_data","worker","--app=cycling_data.celery","--loglevel=info"]
    healthcheck:
      test: ["CMD","/usr/local/bin/python","/app/celery_healthcheck.py"]
    container_name: cycling_test_worker
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
    links:
      - rabbitmq
      - redis
      - fake_ogimet
  rabbitmq:
    image: rabbitmq
    container_name: cycling_test_rabbitmq
    logging:
      driver: journald
  redis:
    image: redis
    container_name: cycling_test_redis
    logging:
      driver: journald
