version: '3.7'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - mysql-data:/var/lib/mysql
    configs:
      - source: mysql-config-cycling.2
        target: /etc/mysql/conf.d/mysql-config-cycling.cnf
    logging:
      driver: journald
    secrets:
      - mysql_root_password
      - source: storage_key.1
        target: /etc/mysql/encryption/keyfile
    ports:
      - '3306:3306'
  cycling_web:
    image: jhaiduce/cycling-pyramid
    ports:
      - "80:80"
    secrets:
      - source: production.ini.1
        target: /run/secrets/production.ini
    logging:
      driver: journald
secrets:
  storage_key.1:
    file: ./storage_key.keyfile
  mysql_root_password:
    file: ./mysql_root_password
  mysql_production_password:
    file: ./mysql_production_password
  pyramid_auth_secret:
    file: ./pyramid_auth_secret
  cycling_admin_password:
    file: ./cycling_admin_password
  production.ini.1:
    file: ./production.ini
volumes:
  cycling-data:
  mysql-data:
configs:
  mysql-config-cycling.2:
    file: ./mysql-config-cycling.cnf
