version: '3.7'
networks:
  default:
    driver: overlay
    driver_opts:
      encrypted: ""
services:
  db:
    image: mariadb
    container_name: cycling_stack_db
    deploy:
      resources:
        reservations:
          memory: 200M
      placement:
        constraints: [node.labels.db == true]
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - mysql-data:/var/lib/mysql
      - type: bind
        source: ./mysql-config-cycling.cnf
        target: /etc/mysql/conf.d/mysql-config-cycling.cnf
    configs:
      - source: mysql-config-cycling.4
        target: /etc/mysql/conf.d/mysql-config-cycling.cnf
    logging:
      driver: journald
    secrets:
      - source: mysql_root_password
        target: mysql_root_password
      - source: storage_key.1
        target: /etc/mysql/encryption/keyfile
      - source: mysql_ca
        target: /etc/my.cnf.d/certificates/ca.pem
      - source: mysql_cert
        target: /etc/my.cnf.d/certificates/server-cert.pem
      - source: mysql_key
        target: /etc/my.cnf.d/certificates/server-key.pem
    ports:
      - '3306:3306'
  cycling_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/cycling-pyramid
    deploy:
      replicas: 2
      resources:
        reservations:
          memory: 300M
    container_name: cycling_stack_cycling_web
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/cycling-pyramid
    deploy:
      replicas: 2
      resources:
        reservations:
          memory: 400M
    command: ["/usr/local/bin/celery","-A","cycling_data","worker","--app=cycling_data.celery","--concurrency","2","--loglevel=info"]
    healthcheck:
      test: ["CMD","/usr/local/bin/python3","/app/celery_healthcheck.py"]
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/cycling-pyramid
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 300M
    command: ["/usr/local/bin/celery","-A","cycling_data","beat","--app=cycling_data.celery","--loglevel=info"]
    working_dir: /app/celerybeat
    healthcheck:
      disable: true
    container_name: cycling_stack_worker
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
  rabbitmq:
    image: rabbitmq
    container_name: cycling_stack_rabbitmq
    deploy:
      resources:
        reservations:
          memory: 200M
    environment:
      RABBITMQ_DEFAULT_USER: cycling
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/cycling_rabbitmq_password
    logging:
      driver: journald
    secrets:
      - source: cycling_rabbitmq_password.2
        target: cycling_rabbitmq_password
  redis:
    image: redis
    container_name: cycling_stack_redis
    logging:
      driver: journald
    deploy:
      resources:
        reservations:
          memory: 100M
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    configs:
      - source: nginx-conf-cycling
        target: /etc/nginx/conf.d/cycling.conf
      - source: nginx-conf-common
        target: /etc/nginx/common.conf
      - source: nginx-conf-common-location
        target: /etc/nginx/conf.d/common-location.conf
      - source: nginx-conf-ssl
        target: /etc/nginx/ssl.conf
      - source: nginx-conf-default
        target: /etc/nginx/conf.d/default.conf
    secrets:
      - source: ssl_certificate
        target: /etc/ssl/private/fullchain.pem
      - source: ssl_certificate_key
        target: /etc/ssl/private/privkey.pem
      - source: dhparams
        target: /etc/nginx/dhparams.pem
secrets:
  storage_key.1:
    file: production_secrets/storage_key.keyfile
  mysql_root_password:
    name: mysql_root_password.1
    file: production_secrets/mysql_root_password
  mysql_production_password.1:
    file: production_secrets/mysql_production_password
  pyramid_auth_secret.1:
    file: production_secrets/pyramid_auth_secret
  cycling_admin_password.1:
    file: production_secrets/cycling_admin_password
  pyramid_main_ini:
    name: production.ini.11
    file: production_secrets/production.ini
  mysql_ca:
    file: production_secrets/ca.pem
  mysql_cert:
    name: mysql_cert.1
    file: production_secrets/server-cert.pem
  mysql_key:
    file: production_secrets/server-key.pem
  cycling_rabbitmq_password.2:
    file: production_secrets/cycling_rabbitmq_password
  dhparams:
    file: nginx/dhparams.pem
  ssl_certificate:
    name: ssl_certificate.4
    file: ./nginx/ssl/fullchain.pem
  ssl_certificate_key:
    name: ssl_certificate_key.4
    file: ./nginx/ssl/privkey.pem
volumes:
  cycling-data:
  mysql-data:
configs:
  mysql-config-cycling.4:
    file: ./mysql-config-cycling.cnf
  nginx-conf-cycling:
    name: nginx-conf-cycling.3
    file: ./nginx/cycling.conf
  nginx-conf-common:
    file: ./nginx/common.conf
  nginx-conf-common-location:
    file: ./nginx/common_location.conf
  nginx-conf-ssl:
    file: nginx/ssl.conf
  nginx-conf-default:
    file: nginx/default.conf
