version: '3.7'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    secrets:
      - source: integration_test.ini
        target: /run/secrets/production.ini
    links:
      - cycling_web
  db:
    image: mariadb
    container_name: cycling_test_db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    volumes:
      - type: bind
        source: ./mysql-config-cycling.cnf
        target: /etc/mysql/conf.d/mysql-config-cycling.cnf
    configs:
      - source: mysql-config-cycling.4
        target: /etc/mysql/conf.d/mysql-config-cycling.cnf
    logging:
      driver: journald
    secrets:
      - source: mysql_root_password.2
        target: mysql_root_password
      - source: storage_key.1
        target: /etc/mysql/encryption/keyfile
      - source: mysql_ca
        target: /etc/my.cnf.d/certificates/ca.pem
      - source: mysql_cert
        target: /etc/my.cnf.d/certificates/server-cert.pem
      - source: mysql_key
        target: /etc/my.cnf.d/certificates/server-key.pem
  cycling_web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/cycling-pyramid
    container_name: cycling_test_cycling_web
    command: ["/app/pyramid_cold_start.sh"]
    secrets:
      - source: integration_test.ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
    links:
      - db
      - rabbitmq
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/cycling-pyramid
    command: ["/usr/bin/celery","-A","cycling_data","worker","--app=cycling_data.celery","--loglevel=info"]
    container_name: cycling_test_worker
    secrets:
      - source: integration_test.ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
    links:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    container_name: cycling_test_rabbitmq
    logging:
      driver: journald
secrets:
  storage_key.1:
    file: ./storage_key.keyfile
  mysql_root_password.2:
    file: ./mysql_root_password_test
  mysql_production_password.3:
    file: ./mysql_production_password_test
  pyramid_auth_secret.1:
    file: ./pyramid_auth_secret
  cycling_admin_password.2:
    file: ./cycling_admin_password_test
  integration_test.ini:
    file: ./integration_test.ini
  mysql_ca:
    file: ./ca.pem
  mysql_cert:
    file: ./server-cert.pem
  mysql_key:
    file: ./server-key.pem
volumes:
  cycling-data:
  mysql-data:
configs:
  mysql-config-cycling.4:
    file: ./mysql-config-cycling.cnf
