FROM python:3.7.2-alpine
FROM node:8-alpine

WORKDIR /app

RUN apk add --update python3

COPY requirements.fake_ogimet.txt /app
RUN pip3 install -r /app/requirements.fake_ogimet.txt
COPY fake_ogimet.py /app

EXPOSE 80

ENV NAME World

RUN addgroup --system appuser && \
    adduser --system -s /bin/sh --no-create-home appuser appuser

RUN apk add libcap

RUN setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/python3.8

USER 1000:1000

CMD ["/usr/bin/python3.8","/app/fake_ogimet.py"]
