name: "Build and test"

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7.2']
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.py }}
          architecture: ${{ matrix.architecture }}
    - run: pip install -r requirements.txt
    - run: pip install '.[testing]'
    - name: Unit tests
      run: pytest -q
    - name: Database migration tests
      run: pytest -q cycling_data/migration_tests.py
  test_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pip install pyotp==2.6.0
    - run: python generate_secrets.py --secretsdir=integration_test_secrets --ini-template=integration_test.ini.tpl --ini-filename=integration_test.ini --openssl-root-config=integration_test_root_config.in --openssl-server-config=integration_test_server_config.in
    - name: Build Docker images
      run: docker-compose -f docker-compose.test_secrets.yml -f docker-compose.db.yml -f docker-compose.test.yml -p ci build
    - name: Migrate database
      run: docker-compose -f docker-compose.test_secrets.yml -f docker-compose.db.yml -f docker-compose.migrate_test.yml -p ci up -d && docker wait ci_migration_1; docker logs ci_migration_1
    - name: Run Docker integration tests
      run: docker-compose -f docker-compose.test_secrets.yml -f docker-compose.db.yml -f docker-compose.test.yml -p ci up -d && docker logs -f ci_sut_1 && docker wait ci_sut_1; docker logs -f ci_sut_1
